// Generated by `pnpm catalog:build` from catalog/products.csv. Do not edit by hand.
import type { Product } from "./catalog";

export const GENERATED_PRODUCTS: Product[] = [
  {
    "slug": "coventry-chronograph-41",
    "name": "Coventry Chronograph 41",
    "brand": "Marlowe & Grey",
    "category": "fashion",
    "priceUsd": 28500,
    "compareAtUsd": 35000,
    "rating": 4.6,
    "reviews": 214,
    "blurb": "A clean, everyday chronograph that reads as a far pricier watch.",
    "details": [
      "41mm brushed stainless steel case, sapphire-coated crystal",
      "Japanese quartz movement, date window at 3 o'clock",
      "Italian leather strap, quick-release spring bars",
      "Water resistant to 50m; 2-year battery life"
    ],
    "art": {
      "kind": "watch",
      "hue": 220
    },
    "image": "/products/coventry-chronograph-41.jpg",
    "badge": "Staff pick"
  },
  {
    "slug": "folio-slim-e-reader",
    "name": "Folio Slim E-Reader",
    "brand": "Folio",
    "category": "tech",
    "priceUsd": 12999,
    "compareAtUsd": 15999,
    "rating": 4.5,
    "reviews": 847,
    "blurb": "A featherlight e-reader with a glare-free display and weeks of battery life.",
    "details": [
      "6.8-inch e-ink display with adjustable warm light",
      "16GB storage, enough for thousands of books",
      "IPX8 waterproof, safe for bath or poolside",
      "4-week battery life on a single charge"
    ],
    "art": {
      "kind": "sneaker",
      "hue": 145
    },
    "image": "/products/folio-slim-e-reader.jpg",
    "badge": "Bestseller"
  },
  {
    "slug": "scalp-revival-drops",
    "name": "Scalp Revival Drops",
    "brand": "Morrow & Sage",
    "category": "beauty",
    "priceUsd": 2800,
    "rating": 4.6,
    "reviews": 342,
    "blurb": "A cooling scalp oil that calms tight roots and preps hair for healthier regrowth.",
    "details": [
      "1.7 fl oz / 50 mL amber glass dropper bottle",
      "Blend of rosemary leaf extract, niacinamide, and jojoba oil",
      "Lightweight, non-greasy formula for daily use",
      "Free from sulfates, parabens, and synthetic fragrance"
    ],
    "art": {
      "kind": "bottle",
      "hue": 35
    },
    "image": "/products/scalp-revival-drops.jpg"
  },
  {
    "slug": "holloway-stoneware-carafe",
    "name": "Holloway Stoneware Carafe",
    "brand": "Morrow & Pine",
    "category": "home",
    "priceUsd": 4400,
    "rating": 4.6,
    "reviews": 328,
    "blurb": "A quiet, hand-finished stoneware carafe that makes tap water feel like a table-setting decision.",
    "details": [
      "Food-safe stoneware, glazed inside and out",
      "Holds 1.2 L; fits standard fridge door",
      "Dishwasher and microwave safe",
      "Available in cream, sage, and terracotta"
    ],
    "art": {
      "kind": "bottle",
      "hue": 32
    },
    "image": "/products/holloway-stoneware-carafe.jpg"
  },
  {
    "slug": "stargazer-camp-hammock",
    "name": "Stargazer Camp Hammock",
    "brand": "Ridgecrest",
    "category": "outdoors",
    "priceUsd": 7999,
    "compareAtUsd": 10999,
    "rating": 4.7,
    "reviews": 1240,
    "blurb": "A roomy, trail-weight hammock that sets up in minutes – no fire required.",
    "details": [
      "20-denier ripstop nylon, 260 g/m²",
      "Capacity: 400 lb / 181 kg",
      "Folds into an integrated 4″ stuff sack",
      "Hanging straps and tree-friendly cord included"
    ],
    "art": {
      "kind": "speaker",
      "hue": 340
    },
    "image": "/products/stargazer-camp-hammock.jpg",
    "badge": "Staff pick"
  },
  {
    "slug": "precision-mug-12oz",
    "name": "Precision Mug 12oz",
    "brand": "HeatCycle",
    "category": "tech",
    "priceUsd": 8950,
    "compareAtUsd": 11999,
    "rating": 4.5,
    "reviews": 843,
    "blurb": "Keeps coffee or tea at your chosen temperature for up to two hours.",
    "details": [
      "12 oz stainless steel interior",
      "Integrated touch display",
      "App presets for your usual drinks",
      "2 hour battery on the mug, charging coaster included"
    ],
    "art": {
      "kind": "mug",
      "hue": 25
    },
    "image": "/products/precision-mug-12oz.jpg"
  },
  {
    "slug": "holloway-stoneware-carafe-2",
    "name": "Holloway Stoneware Carafe",
    "brand": "Morrow & Pine",
    "category": "home",
    "priceUsd": 4800,
    "rating": 4.7,
    "reviews": 214,
    "blurb": "A generous pour for the table, shaped to sit comfortably in hand.",
    "details": [
      "1.5L capacity",
      "Glazed stoneware",
      "Dishwasher safe",
      "H 24cm x W 14cm"
    ],
    "art": {
      "kind": "plant",
      "hue": 210
    },
    "image": "/products/holloway-stoneware-carafe-2.jpg"
  },
  {
    "slug": "ridgecrest-altitude-chair",
    "name": "Ridgecrest Altitude Chair",
    "brand": "Ridgecrest",
    "category": "outdoors",
    "priceUsd": 8999,
    "compareAtUsd": 11999,
    "rating": 4.6,
    "reviews": 1243,
    "blurb": "A supportive camp chair that folds away between trail days.",
    "details": [
      "Aluminum alloy frame, 3.2 lbs",
      "Breathable 600D ripstop polyester seat",
      "Folds to a 5-inch diameter cylinder",
      "Holds up to 250 lbs, fits 5'1\"–6'4\""
    ],
    "art": {
      "kind": "plant",
      "hue": 110
    },
    "image": "/products/ridgecrest-altitude-chair.jpg"
  },
  {
    "slug": "fermented-rice-cleansing-oil",
    "name": "Fermented Rice Cleansing Oil",
    "brand": "Morrow & Sage",
    "category": "beauty",
    "priceUsd": 2400,
    "compareAtUsd": 3000,
    "rating": 4.8,
    "reviews": 2150,
    "blurb": "A silky oil that melts makeup and rinses clean, leaving skin soft and balanced.",
    "details": [
      "Fermented rice water and jojoba ester base.",
      "Dissolves waterproof makeup and SPF instantly.",
      "Emulsifies into a milky lather with water.",
      "200ml / 6.7 fl oz recyclable pump bottle."
    ],
    "art": {
      "kind": "mug",
      "hue": 30
    },
    "image": "/products/fermented-rice-cleansing-oil.jpg",
    "badge": "Bestseller"
  },
  {
    "slug": "reversible-ripstop-puffer",
    "name": "Reversible Ripstop Puffer",
    "brand": "Kestrel & Marsh",
    "category": "fashion",
    "priceUsd": 21800,
    "compareAtUsd": 26800,
    "rating": 4.6,
    "reviews": 432,
    "blurb": "A city-ready puffer that flips between matte and sheen without missing a step.",
    "details": [
      "Shell: 100% recycled ripstop nylon",
      "Fill: 650-fill recycled down",
      "Two-tone reversible design",
      "Machine washable, hang to dry"
    ],
    "art": {
      "kind": "jacket",
      "hue": 145
    },
    "image": "/products/reversible-ripstop-puffer.jpg"
  }
];
