// Step 2: validates catalog/products.csv, generates missing photos, writes src/lib/catalog.generated.ts.
// Usage: pnpm catalog:build [--skip-images] [--redo slug1,slug2]
// Resumable: a photo is only generated when public/products/<slug>.{png,jpg,webp} doesn't exist yet.
import fs from "node:fs";
import type { Product } from "../../src/lib/catalog";
import { GENERATED_TS, IMAGE_DIR, RowSchema, loadEnv, mapLimit, readRows, CSV_PATH } from "./shared";

const IMAGE_MODEL = "google/gemini-3.1-flash-lite-image"; // Nano Banana 2 Lite, via OpenRouter
const OPENROUTER_IMAGES_URL = "https://openrouter.ai/api/v1/images";
const CONCURRENCY = 6;
const MAX_ATTEMPTS = 3;
const EXTENSIONS: Record<string, string> = { "image/png": "png", "image/jpeg": "jpg", "image/webp": "webp" };

// Shared framing so every photo looks like part of the same shop.
const photoPrompt = (subject: string) =>
  `Professional e-commerce studio product photo of ${subject}. Single product, centered, fully in frame, ` +
  `soft diffused lighting, gentle shadow, plain light seamless background, square composition. ` +
  `No text, no logos, no watermark, no people.`;

async function main() {
  loadEnv();
  const skipImages = process.argv.includes("--skip-images");
  const redoArg = process.argv.indexOf("--redo");
  const redo = new Set(redoArg > 0 ? process.argv[redoArg + 1].split(",") : []);

  const rows = readRows();
  if (!rows.length) throw new Error(`No rows in ${CSV_PATH}. Run pnpm catalog:generate first.`);

  // Validate everything before spending money on images.
  const errors: string[] = [];
  const seen = new Set<string>();
  const valid = rows.flatMap((row, i) => {
    const parsed = RowSchema.safeParse(row);
    const line = i + 2; // header is line 1
    if (!parsed.success) {
      errors.push(`line ${line} (${row.slug || "no slug"}): ${parsed.error.issues.map((e) => `${e.path.join(".")} ${e.message}`).join("; ")}`);
      return [];
    }
    if (seen.has(parsed.data.slug)) {
      errors.push(`line ${line}: duplicate slug ${parsed.data.slug}`);
      return [];
    }
    seen.add(parsed.data.slug);
    return [parsed.data];
  });
  if (errors.length) {
    console.error(`${errors.length} invalid row(s) in ${CSV_PATH}:\n  ${errors.join("\n  ")}`);
    process.exit(1);
  }

  fs.mkdirSync(IMAGE_DIR, { recursive: true });
  // The file extension follows whatever format the model returned.
  const findImage = (slug: string) =>
    Object.values(EXTENSIONS).map((ext) => `${IMAGE_DIR}/${slug}.${ext}`).find((f) => fs.existsSync(f));
  const todo = valid.filter((r) => redo.has(r.slug) || !findImage(r.slug));

  if (!skipImages && todo.length) {
    const apiKey = process.env.OPENROUTER_API_KEY;
    if (!apiKey) throw new Error("OPENROUTER_API_KEY is not set (add it to .env.local), or pass --skip-images.");
    console.log(`Generating ${todo.length} photo(s) with ${IMAGE_MODEL}...`);
    let done = 0;
    let cost = 0;
    const failed: string[] = [];
    await mapLimit(todo, CONCURRENCY, async (r) => {
      try {
        const image = await generateImage(apiKey, photoPrompt(r.image_prompt));
        cost += image.cost;
        const old = findImage(r.slug);
        if (old) fs.rmSync(old);
        fs.writeFileSync(`${IMAGE_DIR}/${r.slug}.${image.ext}`, image.bytes);
      } catch (err) {
        if (err instanceof AuthError) throw err;
        failed.push(`${r.slug}: ${err instanceof Error ? err.message : String(err)}`);
      }
      done++;
      if (done % 10 === 0 || done === todo.length) console.log(`  ${done}/${todo.length} ($${cost.toFixed(2)} so far)`);
    });
    if (failed.length) {
      console.warn(`\n${failed.length} photo(s) failed; those products fall back to the illustration. Re-run to retry:\n  ${failed.join("\n  ")}`);
    }
  }

  const products: Product[] = valid.map((r) => ({
    slug: r.slug,
    name: r.name,
    brand: r.brand,
    category: r.category as Product["category"],
    priceUsd: Math.round(r.price_usd * 100),
    ...(r.compare_at_usd !== undefined && { compareAtUsd: Math.round(r.compare_at_usd * 100) }),
    rating: r.rating,
    reviews: r.reviews,
    blurb: r.blurb,
    details: r.details,
    art: { kind: r.art_kind, hue: r.hue },
    ...(findImage(r.slug) && { image: findImage(r.slug)!.replace(/^public/, "") }),
    ...(r.badge && { badge: r.badge }),
  }));

  fs.writeFileSync(
    GENERATED_TS,
    `// Generated by \`pnpm catalog:build\` from ${CSV_PATH}. Do not edit by hand.\n` +
      `import type { Product } from "./catalog";\n\n` +
      `export const GENERATED_PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)};\n`,
  );
  const withPhoto = products.filter((p) => p.image).length;
  console.log(`\nWrote ${products.length} products to ${GENERATED_TS} (${withPhoto} with photos).`);
}

/** One OpenRouter image generation, retried on transient failures. */
async function generateImage(apiKey: string, prompt: string) {
  for (let attempt = 1; ; attempt++) {
    try {
      const res = await fetch(OPENROUTER_IMAGES_URL, {
        method: "POST",
        headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json", "X-Title": "Cartharsis catalog" },
        body: JSON.stringify({ model: IMAGE_MODEL, prompt, n: 1, resolution: "1K", aspect_ratio: "1:1" }),
      });
      const body = await res.json().catch(() => null);
      if (res.status === 401) throw new AuthError();
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${body?.error?.message ?? res.statusText}`);
      const image = body?.data?.[0];
      if (!image?.b64_json) throw new Error("no image returned");
      const ext = EXTENSIONS[image.media_type ?? "image/png"];
      if (!ext) throw new Error(`unexpected format ${image.media_type}`);
      return { bytes: Buffer.from(image.b64_json, "base64"), ext, cost: Number(body.usage?.cost ?? 0) };
    } catch (err) {
      if (err instanceof AuthError || attempt >= MAX_ATTEMPTS) throw err;
      await new Promise((r) => setTimeout(r, 2000 * attempt));
    }
  }
}

class AuthError extends Error {
  constructor() {
    super("Invalid OPENROUTER_API_KEY (check .env.local).");
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
