// Step 2: validates catalog/products.csv, generates missing photos, writes src/lib/catalog.generated.ts.
// Usage: pnpm catalog:build [--skip-images] [--redo slug1,slug2] [--limit N]
// Photos: GPT Image 1 mini (medium) via OpenRouter, 1024x1024 JPEG, ~$0.0086 each.
// Resumable: a photo is only generated when public/products/<slug>.{png,jpg,webp} doesn't exist yet.
import fs from "node:fs";
import type { Product } from "../../src/lib/catalog";
import { SetupError, generateImages } from "./openrouter-images";
import { GENERATED_TS, IMAGE_DIR, RowSchema, loadEnv, readRows, CSV_PATH } from "./shared";

const EXTENSIONS: Record<string, string> = { "image/png": "png", "image/jpeg": "jpg", "image/webp": "webp" };

// Shared framing so every photo looks like part of the same shop.
const photoPrompt = (subject: string) =>
  `Professional e-commerce studio product photo of ${subject}. Single product, centered, fully in frame, ` +
  `soft diffused lighting, gentle shadow, plain light seamless background, square composition. ` +
  `No text, no logos, no watermark, no people.`;

async function main() {
  loadEnv();
  const skipImages = process.argv.includes("--skip-images");
  const redoArg = process.argv.indexOf("--redo");
  const redo = new Set(redoArg > 0 ? process.argv[redoArg + 1].split(",") : []);
  const limitArg = process.argv.indexOf("--limit");
  const limit = limitArg > 0 ? Number(process.argv[limitArg + 1]) : Infinity;

  const rows = readRows();
  if (!rows.length) throw new Error(`No rows in ${CSV_PATH}. Run pnpm catalog:generate first.`);

  // Validate everything before spending money on images.
  const errors: string[] = [];
  const seen = new Set<string>();
  const valid = rows.flatMap((row, i) => {
    const parsed = RowSchema.safeParse(row);
    const line = i + 2; // header is line 1
    if (!parsed.success) {
      errors.push(`line ${line} (${row.slug || "no slug"}): ${parsed.error.issues.map((e) => `${e.path.join(".")} ${e.message}`).join("; ")}`);
      return [];
    }
    if (seen.has(parsed.data.slug)) {
      errors.push(`line ${line}: duplicate slug ${parsed.data.slug}`);
      return [];
    }
    seen.add(parsed.data.slug);
    return [parsed.data];
  });
  if (errors.length) {
    console.error(`${errors.length} invalid row(s) in ${CSV_PATH}:\n  ${errors.join("\n  ")}`);
    process.exit(1);
  }

  fs.mkdirSync(IMAGE_DIR, { recursive: true });
  // The file extension follows whatever format the model returned.
  const findImage = (slug: string) =>
    Object.values(EXTENSIONS).map((ext) => `${IMAGE_DIR}/${slug}.${ext}`).find((f) => fs.existsSync(f));
  // --limit N: only generate the first N missing photos (handy for a quality check before a full run).
  const todo = valid.filter((r) => redo.has(r.slug) || !findImage(r.slug)).slice(0, limit);

  if (!skipImages && todo.length) {
    const apiKey = process.env.OPENROUTER_API_KEY;
    if (!apiKey) throw new Error("OPENROUTER_API_KEY is not set (add it to .env), or pass --skip-images.");
    const slugs = new Set(valid.map((r) => r.slug));
    const save = (slug: string, mimeType: string, bytes: Buffer) => {
      const ext = EXTENSIONS[mimeType];
      if (!slugs.has(slug) || !ext) return;
      const old = findImage(slug);
      if (old) fs.rmSync(old);
      fs.writeFileSync(`${IMAGE_DIR}/${slug}.${ext}`, bytes);
    };
    const jobs = todo.map((r) => ({ key: r.slug, prompt: photoPrompt(r.image_prompt) }));
    console.log(`Generating ${jobs.length} photo(s) with GPT Image 1 mini (~$${(jobs.length * 0.0086).toFixed(2)})...`);
    const failed = await generateImages(apiKey, jobs, save);
    if (failed.length) {
      console.warn(`\n${failed.length} photo(s) failed; those products fall back to the illustration. Re-run to retry:\n  ${failed.join("\n  ")}`);
    }
  }

  const products: Product[] = valid.map((r) => ({
    slug: r.slug,
    name: r.name,
    brand: r.brand,
    category: r.category as Product["category"],
    priceUsd: Math.round(r.price_usd * 100),
    ...(r.compare_at_usd !== undefined && { compareAtUsd: Math.round(r.compare_at_usd * 100) }),
    rating: r.rating,
    reviews: r.reviews,
    blurb: r.blurb,
    details: r.details,
    art: { kind: r.art_kind, hue: r.hue },
    ...(findImage(r.slug) && { image: findImage(r.slug)!.replace(/^public/, "") }),
    ...(r.badge && { badge: r.badge }),
    ...(r.options && { options: r.options }),
  }));

  fs.writeFileSync(
    GENERATED_TS,
    `// Generated by \`pnpm catalog:build\` from ${CSV_PATH}. Do not edit by hand.\n` +
      `import type { Product } from "./catalog";\n\n` +
      `export const GENERATED_PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)};\n`,
  );
  const withPhoto = products.filter((p) => p.image).length;
  console.log(`\nWrote ${products.length} products to ${GENERATED_TS} (${withPhoto} with photos).`);
}

main().catch((err) => {
  if (err instanceof SetupError) console.error(err.message);
  else console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
